### ISSUE TITLE
Similar events link goes to deleted page https://en.wikipedia.org/wiki/HealthCamp

### ISSUE THREAD

**Issue by spdegabrielle** [ukhealthcamp/ukhealthcamp.github.io#23]
Would be really nice to help understand the health camp - I've not been to an unconference before so I don't know what sort of things people talk about?

**Comment by blu3id** [comment]
Thanks. Seems to have been a victim of Wikipedia moderation Archive.org version: https://web.archive.org/web/20170303033713/https://en.wikipedia.org/wiki/HealthCamp though a better introduction to unconferences would be: https://en.wikipedia.org/wiki/Unconference

The https://ukhealthcamp.com/#how-does-it-work section has some useful links a list of previous topics and links to previous sessions and sessions grids.
