### ISSUE TITLE
Weird copy

### ISSUE THREAD

**Issue by DeckOfPandas** [ukhealthcamp/ukhealthcamp.github.io#9]
I think that these two links being adjacent is weird, and initially I didn't realise there were two separate URLS (I thought it might one href with an annoying space in it)

![img_0098](https://user-images.githubusercontent.com/2399432/27842525-aac309f0-6102-11e7-9fb9-182d3b74ed05.PNG)

**Comment by mattstibbs** [comment]
I'd argue the first one is not really necessary, and the link to the Wikipedia page (which links off to the other events) would suffice?

**Comment by mattstibbs** [comment]
(P.S. The Wikipedia page now has a link to UKHealthCamp (as well as HealthCampUK...) 🥇

**Comment by DeckOfPandas** [comment]
I'm only on ipad, so can't Just Fix This, but I agree that one link would suffice so let's have <a href="whatever">similar events</a> in jekyll-ised words?

**Comment by mattstibbs** [comment]
I can fix it - but what are jekyll-ised words? :)

**Comment by DeckOfPandas** [comment]
Sorry, I can never remember jekyll syntax so gave it in html (amusingly I was trying to be clearer...)

**Comment by mattstibbs** [comment]
I think I've done what you wanted anyway...

**Comment by mattstibbs** [comment]
Updated links
